remote_theme: pages-themes/slate@v0.2.0
plugins:
 - jekyll-remote-theme
title: Fundamentos de Sistemas Operativos, Una Aproximación Práctica usando Linux
image: https://honecomp.github.io/figs/portada-libro.png
description: Libro gratuito y libre de sistemas operativos usando Linux
locale: es_ES
show_downloads: false
google-site-verification: UWOK57fyc-5Od58QoXIHqWDkJuCOD9OQU9NsU-te6jI"
