remote_theme: pages-themes/slate@v0.2.0
plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
title: Hone(st) Computing
image: https://honecomp.github.io/figs/portada-libro.png
tagline: libro de sistemas operativos linux gratis libre shell programación C GNU/Linux bash sh scripts scripting pdf
description: libro de sistemas operativos linux gratis libre shell programación C GNU/Linux bash sh scripts scripting pdf
locale: es_ES
show_downloads: false
